### ISSUE TITLE
The MD5 signature could not be verified.

### ISSUE THREAD

**Issue by erralb** [MDSilviu/business-worldpay-gateway-for-woocommerce#1]
Hi,

I am currently trying to setup your plugin. I followed all your instructions to setup WorldPay and the plugin, but I always get the "The MD5 signature could not be verified." error message.

On your plugin settings page, the "Signature Fields" always says : "Select the fields for the signature and save to generate the it", and never shows the string "instId:amount:currency:cartId", even after saving the settings. I entered instId:amount:currency:cartId in the WorldPay settings since it seems to be the correct values... but the error message still shows up.

![screenshot-inlandwaterwaysinternational org 2016-10-06 11-57-17](https://cloud.githubusercontent.com/assets/790992/19148283/33dd2896-8bbc-11e6-9c69-b1e65e4720d0.png)

Could this be linked to the problem?

I'm pretty sure I setup everything correctly on the password / md5 and all the other settings, and the logs do not show any error messages...

Any idea what could go wrong?

Kind regards,
Pierre

**Comment by MDSilviu** [comment]
Hi, you are right there is a bug with the Signature Fields displaying  the correct string and will be fixed soon. Everything else works correctly so if you selected in wordpress admin the correct order to generate this instId:amount:currency:cartId as in the picture and you added this string into Worldpay everything should work fine because the bugged field is just for display purpose and doesn't influence the code that is sent to worldpay. You missed something, check the MD5 secret you added in the WorldPay installation and make sure it matches the one from wordpress admin area.

**Comment by erralb** [comment]
It's weird, I double checked everything, re-saved everything but I'm still getting the error.

I will try to contact WorldPay I guess, casue there's nothing in the WordPress logs...

**Comment by MDSilviu** [comment]
Deactivate the md5 feature from worldpay and remove the secret from wordpress and test it that way. If it works then add them again and try it that way. In the next few days i will update the plugin to fix the visual bug.

**Comment by erralb** [comment]
Haa thanks, I didn't know you could have it blank.

It worked without it, and after re-activating it it now works! Thanks a lot for your support!
